### PR TITLE
Bm active cust

### PR DESCRIPTION
**Pull request by rbmccr**
git fetch origin bm-active-cust

# Description
- added bangazon.com to cors origin whitelist in settings.py
- updated README (orders and customers)

# Steps to test solution
- see last bullet point in README customers section
- make sure you have a customer with no open or closed orders

### CODE REVIEW

**Comment by Nolan-Little** [comment]
👍

**Review by pragmatic-zac — APPROVED** [review]
💯

**Comment by pragmatic-zac** [comment]
looks good to me bm

**Review by amazoradi — COMMENTED** [review]
🐷

**Pull request merged**
